"""Add category to Post model

Revision ID: 7cbf783e90f1
Revises: 4582ad24f5e1
Create Date: 2025-05-08 14:56:07.465954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbf783e90f1'
down_revision = '4582ad24f5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False, server_default='blog'))
        batch_op.create_index(batch_op.f('ix_post_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_created_at'))
        batch_op.drop_index(batch_op.f('ix_post_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
