"""Add first_image_url and thumbnail_url to Post

Revision ID: a32c13391c6b
Revises: 7cbf783e90f1
Create Date: 2025-05-08 17:29:39.582246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32c13391c6b'
down_revision = '7cbf783e90f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('first_image_url')

    # ### end Alembic commands ###
